apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 200-clusterrole.yaml
  - 200-role.yaml
  - 200-serviceaccount.yaml
  - 201-clusterrolebinding.yaml
  - 201-rolebinding.yaml
  - 600-tekton-pruner-default-spec.yaml
  - config-logging.yaml
  - config-observability.yaml
  - controller.yaml
  - config-info.yaml