name: golangci-lint
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:  # yamllint disable-line rule:empty-values

permissions:
  contents: read
  checks: write  # Used to annotate code in the PR

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a  # v5.2.0
        with:
          go-version: stable
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4696ba8babb6127d732c3c6dde519db15edab9ea  # v6.5.1
        with:
          version: v1.62.2
          args: --timeout=10m