name: Pruner kind E2E Tests

on:
  pull_request:
    branches:
      - main
      - release-*

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  k8s:
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        # Keep in sync with the list of supported releases: https://kubernetes.io/releases/
        k8s-version:
        - v1.28.x
        - v1.29.x
        - v1.30.x
        - v1.31.x
        - v1.32.x
    uses: ./.github/workflows/reusable-e2e.yaml
    with:
      k8s-version: ${{ matrix.k8s-version }}
      pipelines-release: v0.70.0
  # This job is for testing the latest LTS version of Tekton Pipelines
  pipelines-lts:
    strategy:
      fail-fast: false # Keep running if one leg fails.
      matrix:
        pipelines-release:
        # This should follow the list of versions from https://github.com/tektoncd/pipeline/blob/main/releases.md#release
        - v0.62.2  # LTS
        - v0.65.2  # LTS
        - v0.70.0
    uses: ./.github/workflows/reusable-e2e.yaml
    with:
      k8s-version: v1.29.x
      pipelines-release: ${{ matrix.pipelines-release }}